---
- name: Install hyprland
  hosts: localhost
  connection: local
  gather_facts: true
  # debugger: on_failed
  any_errors_fatal: true
  vars:
    os_environment:
      - key: EDITOR
        value: vim
  pre_tasks:
    - name: Get running ansible user
      ansible.builtin.set_fact:
        local_user: "{{ lookup('env', 'USER') }}"
        home_dir: "{{ lookup('env', 'HOME') }}"
        work_dir: "{{ playbook_dir | dirname }}"
        cacheable: true
      tags: qa

    - name: Top-level directory in project
      ansible.builtin.shell: git rev-parse --show-toplevel
      register: tld
      tags: qa

    - name: Set tld stdout fact
      ansible.builtin.set_fact:
        tld: "{{ tld.stdout }}"
      tags: qa

    - name: Get OS release
      ansible.builtin.set_fact:
        os_release: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}"
        major_ver: "{{ ansible_distribution_major_version }}"
        distro: "{{ ansible_distribution }}"
      tags: qa
  tasks:
    - name: Add hyprland copr repo
      community.general.copr:
        name: solopasha/hyprland
        state: enabled
      become: true
      when: ansible_os_family == "RedHat"

    - name: Install hyprland
      ansible.builtin.dnf:
        name:
          - hyprland
        update_cache: true
        state: present
      become: true
      when: ansible_os_family == "RedHat"

    - name: Install "Must Have" software
      ansible.builtin.dnf:
        name:
          - dunst
          - mako
          - pipewire
          - polkit-gnome
          - qt5-qtwayland
          - qt6-qtwayland
          - wireplumber
        update_cache: true
        state: present
      become: true
      when: ansible_os_family == "RedHat"
